version: '3.8'

name: tailwind-config-generator
services:
    web-client:
        container_name: web-client #You can change this to your project name
        env_file:
            - .env
        build:
            context: .
            target: development
        image: tailwind-config-generator:latest
        restart: unless-stopped
        command: npm run dev:expose
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 5173:5173
